### PR TITLE
add authentication based on SSH agent

### PR DESCRIPTION
**Pull request by uykusuz**
This change adds a third authentication method, ssh-agent, to the list
of authentication options.
It will try to retrieve the list of signers based on the SSH_AUTH_SOCK
environment variable and setup an authentication method based on the first
encountered signer in that list.

Also it adds the option to let the tunnel guess the authentication method
automatically. In that case it will try to retrieve a method from a key file
and if that fails through the ssh-agent.

### CODE REVIEW

**Comment by rgzr** [comment]
Hey, thank you! This looks nice! :)

I will review it in the next days and merge it.

**Comment by rgzr** [comment]
I merged it and made some modifications later in https://github.com/rgzr/sshtun/commit/a519f41c835102d22ae14166bb9d29ca28ce7e9a to allow encrypted key file auth. Thank you!

**Comment by SwenChan** [comment]
Bravo! It's been a long time.

**Comment by uykusuz** [comment]
cool, I'm glad it found the way in :)

**Pull request merged**
